// task-task-FRONT/components/TaskDialog.tsx
"use client"

import type React from "react"

import { useState, useEffect } from "react"
import { Plus, MessageCircle, Paperclip, Send, Upload, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useTask } from "@/contexts/TaskContext"
import { useTaskActions } from "@/hooks/useTaskActions"
import type { Task } from "@/types"

interface TaskDialogProps {
  isOpen: boolean
  onClose: () => void
  task?: Task | null
  blockId?: string
}

export function TaskDialog({ isOpen, onClose, task, blockId }: TaskDialogProps) {
  const { state } = useTask()
  const { createTask, updateTask, addComment, addAttachment, getUserById } = useTaskActions()

  const [formData, setFormData] = useState({
    title: "",
    description: "",
    priority: "medium" as const,
    assignedUsers: [] as string[],
    dueDate: "",
    tags: "",
  })

  const [newComment, setNewComment] = useState("")
  const [selectedFiles, setSelectedFiles] = useState<File[]>([])

  const isEditMode = !!task

  useEffect(() => {
    if (task) {
      setFormData({
        title: task.title,
        description: task.description,
        priority: task.priority,
        assignedUsers: task.assignedUsers,
        dueDate: task.dueDate ? task.dueDate.toISOString().split("T")[0] : "",
        tags: task.tags.join(", "),
      })
    } else {
      setFormData({
        title: "",
        description: "",
        priority: "medium",
        assignedUsers: [],
        dueDate: "",
        tags: "",
      })
    }
  }, [task])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.title.trim()) return

    const taskData = {
      title: formData.title,
      description: formData.description,
      priority: formData.priority,
      assignedUsers: formData.assignedUsers,
      assignedGroups: [],
      dueDate: formData.dueDate ? new Date(formData.dueDate) : undefined,
      tags: formData.tags
        ? formData.tags
            .split(",")
            .map((tag) => tag.trim())
            .filter((tag) => tag)
        : [],
      status: task?.status || ("todo" as const),
      comments: task?.comments || [],
      attachments: task?.attachments || [],
      createdBy: state.currentUser?.id || "",
    }

    if (isEditMode && task) {
      updateTask(task.id, taskData)
    } else if (blockId) {
      createTask(blockId, taskData)
    }

    onClose()
  }

  const handleAddComment = () => {
    if (!newComment.trim() || !task) return

    addComment(task.id, newComment.trim())
    setNewComment("")
  }

  const handleFileUpload = () => {
    if (selectedFiles.length === 0 || !task) return

    selectedFiles.forEach((file) => {
      addAttachment(task.id, file)
    })

    setSelectedFiles([])
  }

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return "0 Bytes"
    const k = 1024
    const sizes = ["Bytes", "KB", "MB", "GB"]
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return Number.parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i]
  }

  const priorities = [
    { value: "low", label: "Baixa", color: "bg-green-500" },
    { value: "medium", label: "Média", color: "bg-yellow-500" },
    { value: "high", label: "Alta", color: "bg-red-500" },
    { value: "urgent", label: "Urgente", color: "bg-purple-500" },
  ]

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle>{isEditMode ? "Editar Tarefa" : "Nova Tarefa"}</DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="details" className="flex-1 overflow-hidden flex flex-col">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="details">Detalhes</TabsTrigger>
            {isEditMode && <TabsTrigger value="comments">Comentários ({task?.comments.length || 0})</TabsTrigger>}
            {isEditMode && <TabsTrigger value="attachments">Anexos ({task?.attachments.length || 0})</TabsTrigger>}
          </TabsList>

          <TabsContent value="details" className="flex-1 overflow-y-auto">
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <Label htmlFor="title">Título da Tarefa *</Label>
                <Input
                  id="title"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  placeholder="Digite o título da tarefa"
                  required
                />
              </div>

              <div>
                <Label htmlFor="description">Descrição</Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Descreva a tarefa..."
                  rows={4}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="priority">Prioridade</Label>
                  <Select
                    value={formData.priority}
                    onValueChange={(value: any) => setFormData({ ...formData, priority: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {priorities.map((priority) => (
                        <SelectItem key={priority.value} value={priority.value}>
                          <div className="flex items-center gap-2">
                            <div className={`w-3 h-3 rounded-full ${priority.color}`} />
                            {priority.label}
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="dueDate">Data de Vencimento</Label>
                  <Input
                    id="dueDate"
                    type="date"
                    value={formData.dueDate}
                    onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                  />
                </div>
              </div>

              <div>
                <Label htmlFor="assignedUsers">Usuários Atribuídos</Label>
                <Select
                  value={formData.assignedUsers.join(",")}
                  onValueChange={(value) => setFormData({ ...formData, assignedUsers: value ? value.split(",") : [] })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Selecione os usuários">
                      {formData.assignedUsers.length > 0 && (
                        <div className="flex gap-1">
                          {formData.assignedUsers.slice(0, 2).map((userId) => {
                            const user = getUserById(userId)
                            return user ? (
                              <Badge key={userId} variant="secondary" className="text-xs">
                                {user.name}
                              </Badge>
                            ) : null
                          })}
                          {formData.assignedUsers.length > 2 && (
                            <Badge variant="secondary" className="text-xs">
                              +{formData.assignedUsers.length - 2}
                            </Badge>
                          )}
                        </div>
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {state.users.map((user) => (
                      <SelectItem key={user.id} value={user.id}>
                        {user.name} ({user.email})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="tags">Tags</Label>
                <Input
                  id="tags"
                  value={formData.tags}
                  onChange={(e) => setFormData({ ...formData, tags: e.target.value })}
                  placeholder="Separe as tags por vírgula"
                />
              </div>

              <div className="flex justify-end gap-2 pt-4">
                <Button type="button" variant="outline" onClick={onClose}>
                  Cancelar
                </Button>
                <Button type="submit">{isEditMode ? "Atualizar" : "Criar"} Tarefa</Button>
              </div>
            </form>
          </TabsContent>

          {isEditMode && (
            <TabsContent value="comments" className="flex-1 overflow-hidden flex flex-col">
              <div className="flex-1 overflow-y-auto space-y-4 mb-4">
                {task?.comments.length === 0 ? (
                  <div className="text-center py-8 text-gray-500">
                    <MessageCircle className="mx-auto h-12 w-12 mb-2" />
                    <p>Nenhum comentário ainda</p>
                  </div>
                ) : (
                  task?.comments.map((comment) => {
                    const user = getUserById(comment.userId)
                    return (
                      <div key={comment.id} className="flex gap-3">
                        <Avatar className="h-8 w-8">
                          <AvatarImage src={user?.avatar || "/placeholder.svg"} />
                          <AvatarFallback>
                            {user?.name
                              .split(" ")
                              .map((n) => n[0])
                              .join("")}
                          </AvatarFallback>
                        </Avatar>
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="font-medium text-sm">{user?.name}</span>
                            <span className="text-xs text-gray-500">{comment.createdAt.toLocaleString()}</span>
                          </div>
                          <p className="text-sm">{comment.content}</p>
                        </div>
                      </div>
                    )
                  })
                )}
              </div>

              <div className="flex gap-2">
                <Textarea
                  value={newComment}
                  onChange={(e) => setNewComment(e.target.value)}
                  placeholder="Adicionar comentário..."
                  rows={2}
                  className="flex-1"
                />
                <Button onClick={handleAddComment} disabled={!newComment.trim()}>
                  <Send className="h-4 w-4" />
                </Button>
              </div>
            </TabsContent>
          )}

          {isEditMode && (
            <TabsContent value="attachments" className="flex-1 overflow-hidden flex flex-col">
              <div className="flex-1 overflow-y-auto space-y-4 mb-4">
                {task?.attachments.length === 0 ? (
                  <div className="text-center py-8 text-gray-500">
                    <Paperclip className="mx-auto h-12 w-12 mb-2" />
                    <p>Nenhum anexo ainda</p>
                  </div>
                ) : (
                  task?.attachments.map((attachment) => {
                    const user = getUserById(attachment.uploadedBy)
                    return (
                      <div key={attachment.id} className="flex items-center gap-3 p-3 border rounded-lg">
                        <Paperclip className="h-5 w-5 text-gray-500" />
                        <div className="flex-1">
                          <div className="font-medium text-sm">{attachment.fileName}</div>
                          <div className="text-xs text-gray-500">
                            {formatFileSize(attachment.fileSize)} • Enviado por {user?.name} •{" "}
                            {attachment.uploadedAt.toLocaleString()}
                          </div>
                        </div>
                        <div className="flex gap-1">
                          <Button variant="ghost" size="sm">
                            <Upload className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm" className="text-red-600">
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    )
                  })
                )}
              </div>

              <div className="space-y-3">
                <div>
                  <input
                    type="file"
                    multiple
                    onChange={(e) => setSelectedFiles(Array.from(e.target.files || []))}
                    className="hidden"
                    id="file-upload"
                  />
                  <label htmlFor="file-upload">
                    <Button variant="outline" className="w-full bg-transparent" asChild>
                      <span>
                        <Plus className="mr-2 h-4 w-4" />
                        Selecionar Arquivos
                      </span>
                    </Button>
                  </label>
                </div>

                {selectedFiles.length > 0 && (
                  <div className="space-y-2">
                    <h4 className="font-medium text-sm">Arquivos Selecionados:</h4>
                    {selectedFiles.map((file, index) => (
                      <div key={index} className="flex items-center gap-2 text-sm">
                        <Paperclip className="h-4 w-4" />
                        <span>
                          {file.name} ({formatFileSize(file.size)})
                        </span>
                      </div>
                    ))}
                    <Button onClick={handleFileUpload} className="w-full">
                      <Upload className="mr-2 h-4 w-4" />
                      Fazer Upload
                    </Button>
                  </div>
                )}
              </div>
            </TabsContent>
          )}
        </Tabs>
      </DialogContent>
    </Dialog>
  )
}

// task-task-FRONT/src/app/components/task-dialog/task-dialog.component.ts
import { Component, type OnInit } from "@angular/core"
import { type FormBuilder, type FormGroup, Validators } from "@angular/forms"
import type { MatDialogRef } from "@angular/material/dialog"
import type { Task, User } from "../../models/interfaces"
import type { TaskService } from "../../services/task.service"

interface DialogData {
  task?: Task
  blockId?: string
  users: User[]
}

@Component({
  selector: "app-task-dialog",
  templateUrl: "./task-dialog.component.html",
  styleUrls: ["./task-dialog.component.scss"],
})
export class TaskDialogComponent implements OnInit {
  taskForm: FormGroup
  isEditMode: boolean
  priorities = [
    { value: "low", label: "Baixa", color: "#4caf50" },
    { value: "medium", label: "Média", color: "#ff9800" },
    { value: "high", label: "Alta", color: "#f44336" },
    { value: "urgent", label: "Urgente", color: "#9c27b0" },
  ]

  newComment = ""
  selectedFiles: File[] = []

  constructor(
    private fb: FormBuilder,
    private taskService: TaskService,
    public dialogRef: MatDialogRef<TaskDialogComponent>,
    public data: DialogData,
  ) {
    this.isEditMode = !!data.task
    this.taskForm = this.createForm()
  }

  ngOnInit(): void {
    if (this.data.task) {
      this.taskForm.patchValue({
        title: this.data.task.title,
        description: this.data.task.description,
        priority: this.data.task.priority,
        assignedUsers: this.data.task.assignedUsers,
        dueDate: this.data.task.dueDate,
        tags: this.data.task.tags.join(", "),
      })
    }
  }

  private createForm(): FormGroup {
    return this.fb.group({
      title: ["", [Validators.required, Validators.minLength(3)]],
      description: [""],
      priority: ["medium", Validators.required],
      assignedUsers: [[]],
      dueDate: [""],
      tags: [""],
    })
  }

  onSubmit(): void {
    if (this.taskForm.valid) {
      const formValue = this.taskForm.value
      const taskData = {
        ...formValue,
        tags: formValue.tags
          ? formValue.tags
              .split(",")
              .map((tag: string) => tag.trim())
              .filter((tag: string) => tag)
          : [],
        status: this.data.task?.status || "todo",
      }

      this.dialogRef.close(taskData)
    }
  }

  onCancel(): void {
    this.dialogRef.close()
  }

  addComment(): void {
    if (this.newComment.trim() && this.data.task) {
      this.taskService.addComment(this.data.task.id, {
        taskId: this.data.task.id,
        userId: "1", // Current user ID
        content: this.newComment.trim(),
      })
      this.newComment = ""
    }
  }

  onFileSelected(event: any): void {
    const files = event.target.files
    if (files) {
      this.selectedFiles = Array.from(files)
    }
  }

  uploadFiles(): void {
    if (this.selectedFiles.length > 0 && this.data.task) {
      this.selectedFiles.forEach((file) => {
        // Simulate file upload
        const attachment = {
          taskId: this.data.task!.id,
          fileName: file.name,
          fileUrl: URL.createObjectURL(file),
          fileType: file.type,
          fileSize: file.size,
          uploadedBy: "1", // Current user ID
        }

        this.taskService.addAttachment(this.data.task!.id, attachment)
      })

      this.selectedFiles = []
    }
  }

  removeAttachment(attachmentId: string): void {
    // Implementation for removing attachment
    console.log("Remove attachment:", attachmentId)
  }

  getUserName(userId: string): string {
    const user = this.data.users.find((u) => u.id === userId)
    return user ? user.name : "Usuário desconhecido"
  }

  formatFileSize(bytes: number): string {
    if (bytes === 0) return "0 Bytes"
    const k = 1024
    const sizes = ["Bytes", "KB", "MB", "GB"]
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return Number.parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i]
  }
}

<div class="task-dialog">
  <mat-dialog-content>
    <mat-tab-group>
      <!-- Detalhes da Tarefa -->
      <mat-tab label="Detalhes">
        <div class="tab-content">
          <form [formGroup]="taskForm" (ngSubmit)="onSubmit()">
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Título da Tarefa</mat-label>
              <input matInput formControlName="title" placeholder="Digite o título da tarefa">
              <mat-error *ngIf="taskForm.get('title')?.hasError('required')">
                Título é obrigatório
              </mat-error>
              <mat-error *ngIf="taskForm.get('title')?.hasError('minlength')">
                Título deve ter pelo menos 3 caracteres
              </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Descrição</mat-label>
              <textarea 
                matInput 
                formControlName="description" 
                placeholder="Descreva a tarefa..."
                rows="4">
              </textarea>
            </mat-form-field>

            <div class="form-row">
              <mat-form-field appearance="outline" class="half-width">
                <mat-label>Prioridade</mat-label>
                <mat-select formControlName="priority">
                  <mat-option *ngFor="let priority of priorities" [value]="priority.value">
                    <div class="priority-option">
                      <div class="priority-color" [style.background-color]="priority.color"></div>
                      {{ priority.label }}
                    </div>
                  </mat-option>
                </mat-select>
              </mat-form-field>

              <mat-form-field appearance="outline" class="half-width">
                <mat-label>Data de Vencimento</mat-label>
                <input matInput [matDatepicker]="picker" formControlName="dueDate">
                <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
                <mat-datepicker #picker></mat-datepicker>
              </mat-form-field>
            </div>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Usuários Atribuídos</mat-label>
              <mat-select formControlName="assignedUsers" multiple>
                <mat-option *ngFor="let user of data.users" [value]="user.id">
                  {{ user.name }} ({{ user.email }})
                </mat-option>
              </mat-select>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Tags</mat-label>
              <input 
                matInput 
                formControlName="tags" 
                placeholder="Separe as tags por vírgula">
              <mat-hint>Exemplo: frontend, urgente, bug</mat-hint>
            </mat-form-field>
          </form>
        </div>
      </mat-tab>

      <!-- Comentários -->
      <mat-tab label="Comentários" *ngIf="isEditMode">
        <div class="tab-content">
          <div class="comments-section">
            <div class="comments-list" *ngIf="data.task?.comments.length; else noComments">
              <div *ngFor="let comment of data.task.comments" class="comment-item">
                <div class="comment-header">
                  <mat-icon class="user-icon">account_circle</mat-icon>
                  <span class="comment-author">{{ getUserName(comment.userId) }}</span>
                  <span class="comment-date">{{ comment.createdAt | date:'dd/MM/yyyy HH:mm' }}</span>
                </div>
                <div class="comment-content">{{ comment.content }}</div>
              </div>
            </div>
            
            <ng-template #noComments>
              <div class="no-comments">
                <mat-icon>comment</mat-icon>
                <p>Nenhum comentário ainda</p>
              </div>
            </ng-template>

            <div class="add-comment">
              <mat-form-field appearance="outline" class="comment-input">
                <mat-label>Adicionar comentário</mat-label>
                <textarea 
                  matInput 
                  [(ngModel)]="newComment" 
                  placeholder="Digite seu comentário..."
                  rows="3">
                </textarea>
              </mat-form-field>
              <button 
                mat-raised-button 
                color="primary" 
                (click)="addComment()"
                [disabled]="!newComment.trim()">
                <mat-icon>send</mat-icon>
                Comentar
              </button>
            </div>
          </div>
        </div>
      </mat-tab>

      <!-- Anexos -->
      <mat-tab label="Anexos" *ngIf="isEditMode">
        <div class="tab-content">
          <div class="attachments-section">
            <div class="upload-area">
              <input 
                type="file" 
                #fileInput 
                (change)="onFileSelected($event)" 
                multiple 
                style="display: none">
              
              <button 
                mat-stroked-button 
                (click)="fileInput.click()" 
                class="upload-button">
                <mat-icon>attach_file</mat-icon>
                Selecionar Arquivos
              </button>

              <div *ngIf="selectedFiles.length > 0" class="selected-files">
                <h4>Arquivos Selecionados:</h4>
                <div *ngFor="let file of selectedFiles" class="selected-file">
                  <mat-icon>description</mat-icon>
                  <span>{{ file.name }} ({{ formatFileSize(file.size) }})</span>
                </div>
                <button 
                  mat-raised-button 
                  color="primary" 
                  (click)="uploadFiles()"
                  class="upload-confirm">
                  <mat-icon>cloud_upload</mat-icon>
                  Fazer Upload
                </button>
              </div>
            </div>

            <div class="attachments-list" *ngIf="data.task?.attachments.length; else noAttachments">
              <h4>Anexos da Tarefa:</h4>
              <div *ngFor="let attachment of data.task.attachments" class="attachment-item">
                <mat-icon class="file-icon">description</mat-icon>
                <div class="attachment-info">
                  <div class="attachment-name">{{ attachment.fileName }}</div>
                  <div class="attachment-meta">
                    {{ formatFileSize(attachment.fileSize) }} • 
                    Enviado por {{ getUserName(attachment.uploadedBy) }} • 
                    {{ attachment.uploadedAt | date:'dd/MM/yyyy HH:mm' }}
                  </div>
                </div>
                <div class="attachment-actions">
                  <button mat-icon-button matTooltip="Download">
                    <mat-icon>download</mat-icon>
                  </button>
                  <button 
                    mat-icon-button 
                    matTooltip="Remover" 
                    (click)="removeAttachment(attachment.id)"
                    class="delete-button">
                    <mat-icon>delete</mat-icon>
                  </button>
                </div>
              </div>
            </div>

            <ng-template #noAttachments>
              <div class="no-attachments">
                <mat-icon>attach_file</mat-icon>
                <p>Nenhum anexo ainda</p>
              </div>
            </ng-template>
          </div>
        </div>
      </mat-tab>
    </mat-tab-group>
  </mat-dialog-content>

  <mat-dialog-actions align="end">
    <button mat-button (click)="onCancel()">Cancelar</button>
    <button 
      mat-raised-button 
      color="primary" 
      (click)="onSubmit()"
      [disabled]="taskForm.invalid">
      {{ isEditMode ? 'Atualizar' : 'Criar' }} Tarefa
    </button>
  </mat-dialog-actions>
</div>
